general.import = ["~/.config/alacritty/themes-alacritty/themes/one_dark.toml"]

[window]
padding = { x = 4, y = 4 }
decorations = "None"
# dimensions = { columns = 120, lines = 30 }
opacity = 0.95
startup_mode = "Fullscreen"
blur = true

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
size = 12

[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "xterm-256color"
